using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using LootPulse.Models;

namespace LootPulse.Services
{
    public class FilterBuilder
    {
        /// <summary>
        /// Generates a complete .filter file by prepending dynamic market and build rule blocks.
        /// </summary>
        public bool GenerateFilterFile(
            string outputPath, 
            string? baseFilterPath, 
            List<MarketItem> marketItems, 
            PoeBuild? activeBuild,
            int playerLevel,
            double tier1Threshold, // e.g. 100 Chaos
            double tier2Threshold  // e.g. 10 Chaos
        )
        {
            try
            {
                var sb = new StringBuilder();

                // Add header info
                sb.AppendLine("# ==========================================================================");
                sb.AppendLine("# PATH OF EXILE 2 DYNAMIC ECONOMY & BUILD FILTER");
                sb.AppendLine($"# Generated on: {DateTime.Now}");
                sb.AppendLine($"# Current Player Level: {playerLevel}");
                sb.AppendLine("# Generated by: LootPulse Overlay");
                sb.AppendLine("# ==========================================================================\n");

                // 1. Build Item Highlight Section (highest priority - Top of the file)
                if (activeBuild != null)
                {
                    sb.AppendLine("# --------------------------------------------------");
                    sb.AppendLine($"# BUILD HIGHLIGHTS: {activeBuild.Name} (Level {playerLevel})");
                    sb.AppendLine("# --------------------------------------------------");

                    // Highlight specific unique items active at this level
                    var buildUniqueItems = activeBuild.InventorySlots
                        .Where(slot => {
                            if (string.IsNullOrWhiteSpace(slot.ItemName)) return false;
                            if (slot.LevelInterval == null || slot.LevelInterval.Count < 2) return true;
                            return playerLevel >= slot.LevelInterval[0] && playerLevel <= slot.LevelInterval[1];
                        })
                        .Select(slot => slot.ItemName)
                        .Distinct()
                        .ToList();

                    if (buildUniqueItems.Any())
                    {
                        sb.AppendLine("# Active Build Unique Items");
                        sb.AppendLine("Show");
                        sb.AppendLine("    Rarity Unique");
                        sb.Append("    BaseType");
                        foreach (var item in buildUniqueItems)
                        {
                            sb.Append($" \"{item}\"");
                        }
                        sb.AppendLine();
                        sb.AppendLine("    SetTextColor 255 97 36 255   # Custom PoE2 Orange");
                        sb.AppendLine("    SetBorderColor 255 97 36 255");
                        sb.AppendLine("    SetFontSize 45");
                        sb.AppendLine("    PlayAlertSound 1 300");
                        sb.AppendLine("    MinimapIcon 0 Orange Star");
                        sb.AppendLine("    PlayEffect Orange Temp\n");
                    }

                    // Highlight active skill gems at this level
                    var buildGems = activeBuild.Skills
                        .Where(skill => {
                            var name = !string.IsNullOrWhiteSpace(skill.Name) ? skill.Name : GetGemNameFromId(skill.Id);
                            if (string.IsNullOrWhiteSpace(name)) return false;
                            if (skill.LevelInterval == null || skill.LevelInterval.Count < 2) return true;
                            return playerLevel >= skill.LevelInterval[0] && playerLevel <= skill.LevelInterval[1];
                        })
                        .Select(skill => !string.IsNullOrWhiteSpace(skill.Name) ? skill.Name : GetGemNameFromId(skill.Id))
                        .Distinct()
                        .ToList();

                    if (buildGems.Any())
                    {
                        sb.AppendLine("# Active Build Skill Gems");
                        sb.AppendLine("Show");
                        sb.AppendLine("    Class \"Skill Gems\"");
                        sb.Append("    BaseType");
                        foreach (var gem in buildGems)
                        {
                            sb.Append($" \"{gem}\"");
                        }
                        sb.AppendLine();
                        sb.AppendLine("    SetTextColor 255 97 36 255");
                        sb.AppendLine("    SetBorderColor 0 200 255 255 # Teal border");
                        sb.AppendLine("    SetFontSize 40");
                        sb.AppendLine();
                    }
                }

                // 2. Dynamic Economy Highlight Section
                sb.AppendLine("# --------------------------------------------------");
                sb.AppendLine("# DYNAMIC ECONOMY HIGHLIGHTS (poe.ninja)");
                sb.AppendLine("# --------------------------------------------------");

                // Tier 1 Items (Very Valuable: e.g. Divine Orb, Mirror, high-tier uniques)
                var tier1Items = marketItems.Where(i => i.ChaosValue >= tier1Threshold).ToList();
                if (tier1Items.Any())
                {
                    sb.AppendLine("# Tier 1 Economy Items");
                    sb.AppendLine("Show");
                    sb.Append("    BaseType");
                    foreach (var item in tier1Items)
                    {
                        sb.Append($" \"{item.Name}\"");
                    }
                    sb.AppendLine();
                    sb.AppendLine("    SetTextColor 255 0 0 255       # Red text");
                    sb.AppendLine("    SetBorderColor 255 0 0 255     # Red border");
                    sb.AppendLine("    SetBackgroundColor 255 255 255 255 # White background");
                    sb.AppendLine("    SetFontSize 45");
                    sb.AppendLine("    PlayAlertSound 6 300           # Loud drop alert");
                    sb.AppendLine("    MinimapIcon 0 Red Star");
                    sb.AppendLine("    PlayEffect Red\n");
                }

                // Tier 2 Items (Valuable: e.g. Exalted Orb, medium items)
                var tier2Items = marketItems.Where(i => i.ChaosValue >= tier2Threshold && i.ChaosValue < tier1Threshold).ToList();
                if (tier2Items.Any())
                {
                    sb.AppendLine("# Tier 2 Economy Items");
                    sb.AppendLine("Show");
                    sb.Append("    BaseType");
                    foreach (var item in tier2Items)
                    {
                        sb.Append($" \"{item.Name}\"");
                    }
                    sb.AppendLine();
                    sb.AppendLine("    SetTextColor 229 181 96 255     # Gold/Yellow text");
                    sb.AppendLine("    SetBorderColor 229 181 96 255   # Gold border");
                    sb.AppendLine("    SetFontSize 40");
                    sb.AppendLine("    PlayAlertSound 2 300");
                    sb.AppendLine("    MinimapIcon 1 Yellow Star");
                    sb.AppendLine("    PlayEffect Yellow Temp\n");
                }

                // 3. Append the user's existing filter rules if they provided a base file
                if (!string.IsNullOrEmpty(baseFilterPath) && File.Exists(baseFilterPath))
                {
                    sb.AppendLine("# --------------------------------------------------");
                    sb.AppendLine("# APPENDED BASE FILTER RULES");
                    sb.AppendLine("# --------------------------------------------------");
                    var baseFilterContent = File.ReadAllText(baseFilterPath);
                    sb.AppendLine(baseFilterContent);
                }
                else
                {
                    // Fallback to a basic template if no base filter is provided
                    sb.AppendLine("# Fallback basic catch-all rules");
                    sb.AppendLine("Show");
                    sb.AppendLine("    Class \"Currency\"");
                    sb.AppendLine("    SetFontSize 35");
                    sb.AppendLine("Show");
                    sb.AppendLine("    Class \"Waystones\"");
                    sb.AppendLine("    SetFontSize 35");
                    sb.AppendLine("Show");
                    sb.AppendLine("    Rarity >= Rare");
                    sb.AppendLine("    SetFontSize 35");
                    sb.AppendLine("Show");
                    sb.AppendLine("    SetFontSize 30");
                }

                // Write out the filter file
                var directory = Path.GetDirectoryName(outputPath);
                if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
                return true;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error generating filter file: {ex.Message}");
                return false;
            }
        }

        private static string GetGemNameFromId(string id)
        {
            if (string.IsNullOrWhiteSpace(id)) return string.Empty;
            
            // Remove typical path prefixes
            var clean = id.Replace("Metadata/Items/Gem/SkillGem", "")
                          .Replace("Metadata/Items/Gems/SkillGem", "")
                          .Replace("Metadata/Items/Gems/SupportGem", "")
                          .Replace("Metadata/Items/Gem/SupportGem", "")
                          .Replace("Metadata/Items/Gem/", "")
                          .Replace("Metadata/Items/Gems/", "");

            // Split camel case & numbers, e.g. "PlayerDefault1HMace" -> "Player Default 1 H Mace"
            var sb = new StringBuilder();
            for (int i = 0; i < clean.Length; i++)
            {
                if (i > 0)
                {
                    char prev = clean[i - 1];
                    char curr = clean[i];
                    char? next = (i + 1 < clean.Length) ? clean[i + 1] : (char?)null;

                    bool insertSpace = false;

                    // Transition from lower case to upper case: e.g. 'r' to 'D'
                    if (char.IsLower(prev) && char.IsUpper(curr))
                    {
                        insertSpace = true;
                    }
                    // Transition from upper case to upper case followed by lower: e.g. 'H' to 'M' in "1HMace" where next is 'a'
                    else if (char.IsUpper(prev) && char.IsUpper(curr) && next.HasValue && char.IsLower(next.Value))
                    {
                        insertSpace = true;
                    }
                    // Transition from letter to digit: e.g. 't' to '1'
                    else if (char.IsLetter(prev) && char.IsDigit(curr))
                    {
                        insertSpace = true;
                    }
                    // Transition from digit to letter: e.g. '1' to 'H'
                    else if (char.IsDigit(prev) && char.IsLetter(curr))
                    {
                        insertSpace = true;
                    }

                    if (insertSpace)
                    {
                        sb.Append(' ');
                    }
                }
                sb.Append(clean[i]);
            }
            return sb.ToString().Trim();
        }
    }
}
